version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: camper-db
    environment:
      POSTGRES_USER: camper
      POSTGRES_PASSWORD: camper123
      POSTGRES_DB: camper
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      # check if user camper can access databse camper
      test: ["CMD-SHELL", "pg_isready -U camper -d camper"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: camper-minio
    restart: always
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web Console
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: camper-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://camper:camper123@db:5432/camper
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_BUCKET: camper-profile-pics
    ports:
      - "8000:8000"
    command: >
      sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  db_data:
  minio_data:
